### PR TITLE
#127 and #128 bugs fixes

### PR DESCRIPTION
**Pull request by ohad258**

### CODE REVIEW

**Comment by srmeier** [comment]
This looks good, have you tried running the game server and connecting using the official 1299 client? I'm just curious whether it accepts the `uint16`'s in the packet with no issue.

**Comment by ohad258** [comment]
I'm having trouble with using an official client nor random 1299 client... (HackShield etc...).
Would you link me to one that actually works?

**Comment by srmeier** [comment]
Yeah, I can share that. Reach out to me on Skype (bitshift8) because Google flags it if I keep it on my website (due to it looking like a virus).

**Comment by ohad258** [comment]
> This looks good, have you tried running the game server and connecting using the official 1299 client? I'm just curious whether it accepts the `uint16`'s in the packet with no issue.

Tested it on the official client, the stats are not corrupted when i take off and on items :)

**Comment by srmeier** [comment]
> Tested it on the official client, the stats are not corrupted when i take off and on items :)

Thanks @ohad258!

**Pull request merged**
