### PR TITLE
Added 1.298 Tips for Client source

### PR DESCRIPTION
**Pull request by ForcePower**
The actual source was lack of the complete 33 tips which being used in 1.298 (IDS_HELP_TIP_ALL)

### CODE REVIEW

**Comment by srmeier** [comment]
For some reason the pull request is nothing but my previous commits. There aren't any commits here from you... I have no idea why

**Comment by onurcanbektas** [comment]
because amir's pull request is from his develop branch to your master branch, and his commit are in his master branch.

**Comment by ForcePower** [comment]
onurcanbektas can you come to the skype and help us for a sec?

**Comment by onurcanbektas** [comment]
sure, add me on Skype.I guess I sent it on the forum.

**Comment by ForcePower** [comment]
added but it seems its not u so if u can add me amir_rosen127

**Comment by onurcanbektas** [comment]
Since, you have opened the second pull request, you should close this one.

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#6

**Pull request closed without merging**
