### PR TITLE
Lua Bindings and 21.lua corrections

### PR DESCRIPTION
**Pull request by mjsamet**
Added Lua Bindings: **CheckExistEvent, CheckNoExistEvent** for quests
**EventID  21130** corrections

Added CheckExistEvent, CheckNoExistEvent, ZoneChange to **Evt Converter**

### CODE REVIEW

**Comment by srmeier** [comment]
Looks good to me! Looking over the code I believe you also addressed @twostars comments made in PR #119. Will merge this, thank you for your hard work.

**Comment by onurcanbektas** [comment]
Does any one knows why we are still keeping lua files in the repo ?

**Comment by srmeier** [comment]
> Does any one knows why we are still keeping lua files in the repo ?

Good question, they are required for questing but if people are able to generate them automatically from the EVTs then perhaps we can remove them from the repo.

**Comment by onurcanbektas** [comment]
Then perhaps we should keep them. Beginners might have some problems about generating them.

**Comment by tra666** [comment]
Nice

**Pull request merged**
