### PR TITLE
Mainly, added some functionality to EvtConverter and 4 lua functions are added to server side.

### PR DESCRIPTION
**Pull request by onurcanbektas**

### CODE REVIEW

**Comment by onurcanbektas** [comment]
By the way, about the problem that I mentioned on skype, actually it wasn't a problem but rather the fact that _LUA_WRAPPER_USER_FUNCTION is not working, which is something that I didn't include to the code, so I just wanted to clarify.

**Comment by onurcanbektas** [comment]
By the way, is there a problem in the pull request ?

**Comment by srmeier** [comment]
It looks like this branch has conflicts that need resolving. I haven't had time to check this out in detail yet.

**Comment by srmeier** [comment]
The easiest way for me to resolve this is to just email me / send via Skype your version of the EvtConverter and tell me which EVT flags you implemented. I'll add them to the master branch and close the pull request. I'm going to merge the master branch into the development branch. Please push to the develop branch in the future.

**Comment by onurcanbektas** [comment]
I had to reinstall the host system because the host machine hadn't been opening, so I don't have the project locally, but if it will solve the problem, I can create it to develop branch ?

**Comment by onurcanbektas** [comment]
By the way, for the list of flags you can look the description of the commits because I most probably wrote the every flag that I added.

**Comment by srmeier** [comment]
Ok since you don't have the project locally I'll update the files based on your commits here and close the request once that's done.

**Comment by onurcanbektas** [comment]
ok let me know when you finish

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#5

**Pull request closed without merging**
